#!/usr/bin/env python

import msgpack
import redis
import sys
import socket

def fetch ():
    r = redis.Redis (host='127.0.0.1', port=6379, db=0)
    obj = r.keys ('*')
    unpkr = msgpack.Unpacker()
    
    for k in obj:
        if len(k) == 4:    af = socket.AF_INET
        elif len(k) == 16: af = socket.AF_INET6
        else: continue  # unsupported address format
        addr = socket.inet_ntop (af, k)
        print addr, '\t',

        names = []
        for m in r.lrange (k, 0, -1):
            data = msgpack.unpackb (m)
            if 'name' in data: names.append (data['name'])

        print list (set (names))




if __name__ == '__main__':
    fetch ()
